catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^7.6.0
    '@antfu/ni': ^28.2.0
    '@antfu/utils': ^9.3.0
    '@eslint/config-inspector': ^1.4.2
    '@eslint/markdown': ^7.5.1
    '@types/lodash.merge': ^4.6.9
    '@types/node': ^25.3.0
    '@types/semver': ^7.7.1
    '@typescript-eslint/rule-tester': ^8.56.1
    '@typescript-eslint/types': ^8.56.1
    '@typescript-eslint/typescript-estree': ^8.56.1
    '@typescript-eslint/utils': ^8.56.1
    '@vitest/ui': ^4.0.18
    bumpp: ^10.4.1
    chokidar: ^5.0.0
    eslint: ^10.0.2
    eslint-vitest-rule-tester: ^3.1.0
    fast-glob: ^3.3.3
    lint-staged: ^16.2.7
    lodash.merge: 4.6.2
    pnpm: ^10.30.2
    rimraf: ^6.1.3
    semver: ^7.7.4
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.3
    typescript: ^5.9.3
    vite: ^7.3.1
    vitest: ^4.0.18
  docs:
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.4
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.2.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    unocss: ^66.6.0
    unplugin-vue-components: ^31.0.0
    vitepress: ^1.6.4
    vue: ^3.5.29
  prod:
    '@es-joy/jsdoccomment': ^0.84.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
