packages:
  - playground
  - docs
  - integrations/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.15.0
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@es-joy/jsdoccomment': ^0.50.2
  '@eslint/config-inspector': ^1.1.0
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@types/lodash.merge': ^4.6.9
  '@types/node': ^24.0.3
  '@types/semver': ^7.7.0
  '@types/vscode': ^1.101.0
  '@typescript-eslint/rule-tester': ^8.34.1
  '@typescript-eslint/typescript-estree': ^8.34.1
  '@typescript-eslint/utils': ^8.34.1
  '@unocss/reset': ^66.2.3
  '@vitest/ui': ^3.2.4
  '@vscode/vsce': ^3.5.0
  '@vueuse/core': ^13.4.0
  bumpp: ^10.2.0
  eslint: ^9.29.0
  eslint-vitest-rule-tester: ^2.2.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  lint-staged: ^16.1.2
  lodash.merge: 4.6.2
  nip: ^1.1.0
  pnpm: ^10.12.1
  reactive-vscode: ^0.3.0
  rimraf: ^6.0.1
  semver: ^7.7.2
  simple-git-hooks: ^2.13.0
  tsdown: ^0.12.8
  tsup: ^8.5.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.2.3
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vitepress: ^1.6.3
  vitest: ^3.2.4
  vscode-ext-gen: ^1.0.2
  vue: ^3.5.17
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
